name: Node Unit Tests
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v1
      shell: bash
    - name: Create Checksum
      run: sh .github/scripts/checksum.sh /tmp/checksums.txt
      shell: bash
    - name: Install Root Dependencies
      run: npm install --ignore-scripts --unsafe-perm
      shell: bash
    - name: Boostrap Dependencies
      run: npx lerna bootstrap --no-ci
      env:
        NPM_CONFIG_UNSAFE_PERM: true
      shell: bash
    - name: Unit tests
      run: npm run test
      shell: bash