name: Unit Tests
on:
  push:
    branches: [master]
  pull_request:

jobs:
  node8:
    runs-on: ubuntu-latest
    container:
      image: node:8
    steps:
      - uses: actions/checkout@v1
      - name: Node 8 Unit Tests
        uses: open-telemetry/opentelemetry-js/.github/node_unit_tests@v1
  # node10:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:10
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Node 10 Unit Tests
  #       uses: ./.github/node_unit_tests
  # node12:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:12
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Node 12 Unit Tests
  #       uses: ./.github/node_unit_tests
  #     - name: report coverage
  #       run: npm run codecov
  # node14:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:14
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Node 14 Unit Tests
  #       uses: ./.github/node_unit_tests