name: Unit Tests
on:
  push:
    branches: [master]
  pull_request:

jobs:
  node8:
    runs-on: ubuntu-latest
    container:
      image: node:8
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/node_unit_tests
  # node10:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/node_unit_tests
  # node12:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:12
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/node_unit_tests
  # node14:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:14
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/node_unit_tests